name: Flutter Web Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # IMPORTANT: Use 'flutter' instead of 'dart'
      - name: Install dependencies
        run: flutter pub get
        # If your pubspec.yaml is inside a folder, uncomment the next line:
        # working-directory: ./flutter_application_1 

      - name: Build Web
        run: flutter build web --release --base-href "/g-task/"
        # working-directory: ./flutter_application_1

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web # If in subfolder, use ./flutter_application_1/build/web
          